import json
import os
import sqlite3
import smtplib
from datetime import datetime
from email.message import EmailMessage
from functools import wraps
from pathlib import Path

from flask import Flask, jsonify, request, send_file
from flask_cors import CORS
from dotenv import load_dotenv
import psycopg
from psycopg.rows import dict_row

BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "locations.db"
HTML_PATH = BASE_DIR / "konumum.html"
ADMIN_HTML_PATH = BASE_DIR / "admin.html"

load_dotenv(BASE_DIR / ".env")

app = Flask(__name__, static_folder=str(BASE_DIR), static_url_path="")
CORS(app, resources={r"/api/*": {"origins": "*"}})


def init_db():
    if os.getenv("DATABASE_URL"):
        with psycopg.connect(os.environ["DATABASE_URL"]) as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS public.locations (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        lat DOUBLE PRECISION NOT NULL,
                        lon DOUBLE PRECISION NOT NULL,
                        accuracy DOUBLE PRECISION,
                        timestamp TIMESTAMPTZ NOT NULL,
                        created_at TIMESTAMPTZ DEFAULT NOW()
                    )
                    """
                )
        return

    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS locations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                lat REAL NOT NULL,
                lon REAL NOT NULL,
                accuracy REAL,
                timestamp TEXT NOT NULL,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
            """
        )


init_db()


def get_db_connection():
    if os.getenv("DATABASE_URL"):
        return psycopg.connect(os.environ["DATABASE_URL"], row_factory=dict_row)

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def admin_required(view):
    @wraps(view)
    def wrapped_view(*args, **kwargs):
        username = os.getenv("ADMIN_USERNAME", "").strip()
        password = os.getenv("ADMIN_PASSWORD", "")
        credentials = request.authorization
        if not username or not password:
            return jsonify({"error": "Admin credentials are not configured"}), 503
        if not credentials or credentials.username != username or credentials.password != password:
            response = jsonify({"error": "Authentication required"})
            response.status_code = 401
            response.headers["WWW-Authenticate"] = 'Basic realm="Location Admin"'
            return response
        return view(*args, **kwargs)

    return wrapped_view


def send_email(lat, lon, accuracy, timestamp):
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = (os.getenv("SMTP_USER", "") or "").strip()
    smtp_password = (os.getenv("SMTP_PASSWORD", "") or "").strip()
    to_email = (os.getenv("TO_EMAIL", "erenakc69@gmail.com") or "erenakc69@gmail.com").strip()

    placeholder = "PASTE_YOUR_GMAIL_APP_PASSWORD_HERE"
    if not smtp_user or not smtp_password or smtp_password == placeholder or "PASTE_" in smtp_password.upper():
        return {
            "status": "skipped",
            "message": "SMTP credentials are not set. Replace the placeholder in .env with a real Gmail app password to enable automatic email delivery.",
        }

    map_url = f"https://www.google.com/maps?q={lat},{lon}"
    subject = "Kişisel konum takibi"
    body = (
        f"Tarih: {timestamp}\n"
        f"Koordinatlar: {lat:.6f}, {lon:.6f}\n"
        f"Doğruluk: ±{accuracy} m\n"
        f"Harita: {map_url}"
    )

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = to_email
    msg.set_content(body)

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.starttls()
        server.login(smtp_user, smtp_password)
        server.send_message(msg)

    return {"status": "sent"}


@app.get("/api/health")
def health():
    return jsonify({"status": "ok"})


@app.get("/api/history")
def history():
    conn = get_db_connection()
    query = "SELECT lat, lon, accuracy, timestamp FROM locations ORDER BY id DESC LIMIT 20"
    rows = conn.execute(query).fetchall()
    conn.close()
    return jsonify([
        {
            "lat": row["lat"],
            "lon": row["lon"],
            "accuracy": row["accuracy"],
            "timestamp": row["timestamp"],
        }
        for row in rows
    ])


@app.get("/api/admin/history")
@admin_required
def admin_history():
    conn = get_db_connection()
    rows = conn.execute(
        "SELECT id, lat, lon, accuracy, timestamp, created_at FROM locations ORDER BY id DESC LIMIT 100"
    ).fetchall()
    conn.close()
    return jsonify([
        {
            "id": row["id"],
            "lat": row["lat"],
            "lon": row["lon"],
            "accuracy": row["accuracy"],
            "timestamp": row["timestamp"],
            "created_at": row["created_at"],
        }
        for row in rows
    ])


@app.post("/api/location")
def receive_location():
    payload = request.get_json(silent=True) or {}
    lat = payload.get("lat")
    lon = payload.get("lon")
    accuracy = payload.get("accuracy")
    timestamp = payload.get("timestamp") or datetime.utcnow().isoformat()

    if lat is None or lon is None:
        return jsonify({"error": "lat and lon are required"}), 400

    conn = get_db_connection()
    query = "INSERT INTO locations (lat, lon, accuracy, timestamp) VALUES (%s, %s, %s, %s)" if os.getenv("DATABASE_URL") else "INSERT INTO locations (lat, lon, accuracy, timestamp) VALUES (?, ?, ?, ?)"
    conn.execute(
        query,
        (float(lat), float(lon), float(accuracy) if accuracy is not None else None, timestamp),
    )
    conn.commit()
    if os.getenv("DATABASE_URL"):
        location_id = conn.execute("SELECT id FROM locations ORDER BY id DESC LIMIT 1").fetchone()["id"]
    else:
        location_id = conn.execute("SELECT last_insert_rowid() AS id").fetchone()["id"]
    conn.close()

    email_result = send_email(float(lat), float(lon), float(accuracy) if accuracy is not None else 0, timestamp)
    return jsonify({
        "status": "ok",
        "id": location_id,
        "email": email_result,
        "timestamp": timestamp,
    })


@app.get("/")
def index():
    return send_file(HTML_PATH, mimetype="text/html")


@app.get("/admin")
@admin_required
def admin():
    return send_file(ADMIN_HTML_PATH, mimetype="text/html")


if __name__ == "__main__":
    init_db()
    app.run(host="0.0.0.0", port=int(os.getenv("PORT", "5000")), debug=False)
